apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: wso2
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-container
        image: usman10p/helloworld-wso2-img:latest
        ports:
        - containerPort: 8080

